import 'package:supabase_flutter/supabase_flutter.dart';
import '../../../../core/error/failures.dart';
import '../models/message.dart';

class MessageRepository {
  final SupabaseClient _client = Supabase.instance.client;

  // Stream of messages for an album (real-time)
  Stream<List<Message>> messagesStream(String albumId, {int limit = 50}) {
    return _client
        .from('messages')
        .stream(primaryKey: ['id'])
        .eq('album_id', albumId)
        .order('created_at', ascending: false)
        .limit(limit)
        .map((data) => data.map((m) => Message.fromMap(m)).toList());
  }

  // One-time fetch (for initial load or pagination)
  Future<List<Message>> getMessages(
    String albumId, {
    int limit = 50,
    DateTime? before,
  }) async {
    try {
      var query = _client
          .from('messages')
          .select()
          .eq('album_id', albumId);

      if (before != null) {
        query = query.lt('created_at', before.toIso8601String());
      }

      final data = await query
          .order('created_at', ascending: false)
          .limit(limit);

      return data.map((m) => Message.fromMap(m)).toList();
    } on PostgrestException catch (e) {
      throw MessageFailure(e.message);
    } catch (e) {
      throw MessageFailure(e.toString());
    }
  }

  // Send a new message
  Future<(Message?, Failure?)> sendMessage({
    required String albumId,
    required String userId,
    required String content,
    MessageType type = MessageType.text,
    Map<String, dynamic> metadata = const {},
  }) async {
    try {
      final message = Message(
        id: '', // Will be generated by DB
        albumId: albumId,
        userId: userId,
        content: content,
        type: type,
        metadata: metadata,
        createdAt: DateTime.now(),
      );

      final data = await _client
          .from('messages')
          .insert(message.toMap())
          .select()
          .single();

      return (Message.fromMap(data), null);
    } on PostgrestException catch (e) {
      return (null, MessageFailure(e.message));
    } catch (e) {
      return (null, MessageFailure(e.toString()));
    }
  }

  // Send system message (internal use)
  Future<void> sendSystemMessage({
    required String albumId,
    required String event,
    String? targetUserId,
    String? targetUserEmail,
    Map<String, dynamic> additionalMetadata = const {},
  }) async {
    final content = _systemMessageContent(event, targetUserEmail);
    final metadata = <String, dynamic>{
      'event': event,
      ...additionalMetadata,
    };
    if (targetUserId != null) metadata['target_user_id'] = targetUserId;
    if (targetUserEmail != null) metadata['target_user_email'] = targetUserEmail;

    await _client.from('messages').insert({
      'album_id': albumId,
      'user_id': Supabase.instance.client.auth.currentUser?.id ?? 'system',
      'content': content,
      'type': 'system',
      'metadata': metadata,
    });
  }

  String _systemMessageContent(String event, String? userEmail) {
    switch (event) {
      case 'member_joined':
        return '$userEmail joined the journal';
      case 'member_left':
        return '$userEmail left the journal';
      case 'trip_ended':
        return 'The trip has ended. Confession notes are now revealed!';
      case 'confession_unlocked':
        return 'Confession notes are now visible to everyone';
      default:
        return event;
    }
  }

  // Mark message as read (if needed for read receipts)
  Future<void> markAsRead(String messageId) async {
    // Could add a read_receipts table if needed
  }

  // Delete message
  Future<Failure?> deleteMessage(String messageId) async {
    try {
      await _client.from('messages').delete().eq('id', messageId);
      return null;
    } on PostgrestException catch (e) {
      return MessageFailure(e.message);
    } catch (e) {
      return MessageFailure(e.toString());
    }
  }
}