// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, unused_import
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeavwaT4JL5kvJECXjijHra1PEacuDbvE',
    appId: '1:754599012373:android:5f5ab11b50de7c4332461c',
    messagingSenderId: '754599012373',
    projectId: 'relog2-614b7',
    storageBucket: 'relog2-614b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe2bw8IBEs4XtWsGrJLf5xdHa2AH1C3BE',
    appId: '1:754599012373:ios:d39f29823a189b9732461c',
    messagingSenderId: '754599012373',
    projectId: 'relog2-614b7',
    storageBucket: 'relog2-614b7.firebasestorage.app',
    iosBundleId: 'com.relog2.relog2',
  );
}